topology:
  handler: src/admin/handler.topology
  events:
    - http:
        path: /admin/topology
        method: get
        cors:
          origin: "*" # <-- Specify allowed origin
          headers: # <-- Specify allowed headers
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: false
registerServer:
  handler: src/admin/handler.registerServer
  events:
    - http:
        path: /admin/server
        method: post
