producerStateChangeEvent:
  handler: src/sfu/eventHandler.producerStateChange
  events:
    - http:
        path: /event/producer/state/change
        method: post
consumerStateChangeEvent:
  handler: src/sfu/eventHandler.consumerStateChange
  events:
    - http:
        path: /event/consumer/state/change
        method: post
