participantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.PARTICIPANT_TABLE}
    AttributeDefinitions:
      - AttributeName: token
        AttributeType: S
    KeySchema:
      - AttributeName: token
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
serverTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.SERVER_TABLE}
    AttributeDefinitions:
      - AttributeName: ip
        AttributeType: S
      - AttributeName: port
        AttributeType: N
    KeySchema:
      - AttributeName: ip
        KeyType: HASH
      - AttributeName: port
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
connectionTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.CONNECTION_TABLE}
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
streamTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.STREAM_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
      - AttributeName: producerId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
      - AttributeName: producerId
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
streamConsumerTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.STREAM_CONSUMER_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
      - AttributeName: consumerId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
      - AttributeName: consumerId
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
