participantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.PARTICIPANT_TABLE}
    AttributeDefinitions:
      - AttributeName: token
        AttributeType: S
    KeySchema:
      - AttributeName: token
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
serverTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.SERVER_TABLE}
    AttributeDefinitions:
      - AttributeName: ip
        AttributeType: S
      - AttributeName: port
        AttributeType: N
    KeySchema:
      - AttributeName: ip
        KeyType: HASH
      - AttributeName: port
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
connectionTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.CONNECTION_TABLE}
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
streamTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.STREAM_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
      - AttributeName: producerId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
      - AttributeName: producerId
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
streamConsumerTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.STREAM_CONSUMER_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
      - AttributeName: consumerId
        AttributeType: S
      - AttributeName: sourceTransportId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
      - AttributeName: consumerId
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: ${self:provider.environment.STREAM_CONSUMER_TABLE_INDEX_SOURCE_TRANSPORT}
        KeySchema:
          - AttributeName: sourceTransportId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
participantSendTransport:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.SEND_TRANSPORT_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
participantRecvTransport:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.RECV_TRANSPORT_TABLE}
    AttributeDefinitions:
      - AttributeName: transportId
        AttributeType: S
    KeySchema:
      - AttributeName: transportId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
