org: moroine
app: broadcast-service-api
service:
  name: broadcast-service-api

plugins:
  # - serverless-dotenv-plugin
  - serverless-stage-manager
  - serverless-pseudo-parameters
  - serverless-plugin-monorepo
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-dynamodb-local
  # - serverless-offline
  - "@amfa-team/serverless-offline"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: eu-west-3
  profile: picnic # aws credential profile name
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  environment:
    SECRET: ${env:SECRET, 'super-SECRET'}
    CONNECTION_TABLE: "${self:service.name}-${self:provider.stage}-connection"
    PARTICIPANT_TABLE: "${self:service.name}-${self:provider.stage}-participants"
    SERVER_TABLE: "${self:service.name}-${self:provider.stage}-server"
    STREAM_TABLE: "${self:service.name}-${self:provider.stage}-stream"
    STREAM_CONSUMER_TABLE: "${self:service.name}-${self:provider.stage}-consumer"
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:service.name}-${self:provider.stage}-*"
package:
  individually: true

functions:
  - ${file(./serverless/adminRoutes.yml)}
  - ${file(./serverless/websocket.yml)}

resources:
  Resources: ${file(./serverless/resources.yml)}

custom:
  serverless-offline:
    useChildProcesses: true
    webSocketHardTimeout: 300
    webSocketIdleTimeout: 120
  dynamodb:
    stages:
      - dev
    start:
      port: 9005
      isMemory: true
      migrate: true
  stages:
    - dev
    - production
    - staging
