import type { Document } from "dynamoose/dist/Document";
import type { Connection } from "../../../types/src/db/connection";
import type { Participant } from "../../../types/src/db/participant";
import type { RecvTransport } from "../../../types/src/db/recvTransport";
import type { SendTransport } from "../../../types/src/db/sendTransport";
import type { Server } from "../../../types/src/db/server";
import type { StreamInfo } from "../../../types/src/db/stream";
import type { StreamConsumerInfo } from "../../../types/src/db/streamConsumer";
export declare type ServerDocument = Server & Document;
export declare const serverSchema: import("dynamoose/dist/Schema").Schema;
export declare const ServerModel: import("dynamoose/dist/General").ModelType<ServerDocument>;
export declare type ParticipantDocument = Participant & Document;
export declare const participantSchema: import("dynamoose/dist/Schema").Schema;
export declare const ParticipantModel: import("dynamoose/dist/General").ModelType<ParticipantDocument>;
export declare type ConnectionDocument = Connection & Document;
export declare const connectionSchema: import("dynamoose/dist/Schema").Schema;
export declare const ConnectionModel: import("dynamoose/dist/General").ModelType<ConnectionDocument>;
export declare type RecvTransportDocument = RecvTransport & Document;
export declare const recvTransportSchema: import("dynamoose/dist/Schema").Schema;
export declare const RecvTransportModel: import("dynamoose/dist/General").ModelType<RecvTransportDocument>;
export declare type SendTransportDocument = SendTransport & Document;
export declare const sendTransportSchema: import("dynamoose/dist/Schema").Schema;
export declare const SendTransportModel: import("dynamoose/dist/General").ModelType<SendTransportDocument>;
export declare type StreamDocument = StreamInfo & Document;
export declare const streamSchema: import("dynamoose/dist/Schema").Schema;
export declare const StreamModel: import("dynamoose/dist/General").ModelType<StreamDocument>;
export declare type StreamConsumerDocument = StreamConsumerInfo & Document;
export declare const streamConsumerSchema: import("dynamoose/dist/Schema").Schema;
export declare const StreamConsumerModel: import("dynamoose/dist/General").ModelType<StreamConsumerDocument>;
//# sourceMappingURL=schema.d.ts.map