name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  install: # Runs install once before everything to create & save cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
  deploy-api:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
      - name: serverless deploy
        working-directory: ./packages/api
        run: yarn serverless deploy --stage production
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SECRET: ${{ secrets.PRODUCTION_CLUSTER_SECRET }}
  deploy-server:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Create SSH Private Key
        run: echo "$SSH_KEY" > ~/.ssh/picnic && chmod 600 ~/.ssh/picnic
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/picnic
        name: register ssh agent
      - run: node dumpEnv.js
        name: generate env file
        working-directory: ./packages/server
        env:
          CLUSTER_API: ${{ secrets.PRODUCTION_CLUSTER_API }}
          CLUSTER_SECRET: ${{ secrets.PRODUCTION_CLUSTER_SECRET }}
          PUBLIC_IP: "15.237.3.235"
      - run: "scp -i ~/.ssh/picnic -o 'StrictHostKeyChecking=no' server-env ubuntu@15.237.3.235:~/server-env"
        name: upload env vars
        working-directory: ./packages/server
      - name: pm2 deploy
        working-directory: ./packages/server
        run: yarn pm2 deploy production --force
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: Mediasoup Server deployed
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: Mediasoup Server FAILED
          SLACK_COLOR: "#2eb886"
        if: failure()
  deploy-client-public:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
      - name: build public website
        working-directory: ./packages/client
        run: yarn build:public
        env:
          WS_API: ${{ secrets.PRODUCTION_WEBSOCKET }}
          HTTP_API: ${{ secrets.PRODUCTION_CLUSTER_API }}
      - name: update stack
        working-directory: ./packages/client
        run: yarn serverless deploy --stage production
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: deploy public
        working-directory: ./packages/client
        run: yarn serverless client deploy --stage production --no-confirm
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: Client test page deployed
  deploy-client-sdk:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deploy-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-production-
            ${{ runner.os }}-
      - run: yarn install
      - name: publish sdk
        working-directory: ./packages/client
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
