name: Deploy Staging

on:
  push:
    branches:
      - develop
      - bugfix/build

env:
  SERVER_PUBLIC_IP: "15.236.168.171"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: echo -e "//npm.pkg.github.com/:_authToken=$NPM_TOKEN\n@amfa-team:registry=https://npm.pkg.github.com" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn install
      - run: echo -e "SENTRY_DNS=$SENTRY_DNS" >> packages/example/.env
        env:
          SENTRY_DNS: ${{ secrets.SENTRY_EXAMPLE_DNS }}
      - run: echo -e "WS_API=$WS_API" >> packages/example/.env
        env:
          WS_API: ${{ secrets.STAGING_WEBSOCKET }}
      - run: echo -e "HTTP_API=$HTTP_API" >> packages/example/.env
        env:
          HTTP_API: ${{ secrets.STAGING_CLUSTER_API }}
      - run: echo -e "SENTRY_ENVIRONMENT=$ENVIRONMENT_NAME" >> packages/example/.env
        env:
          SENTRY_ENVIRONMENT: staging
      - name: build
        run: yarn build
        env:
          SENTRY_ENVIRONMENT: staging
      - name: publish sdk
        run: yarn npm:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
      - name: deploy
        working-directory: ./packages/example
        run: yarn aws:profile:set --stage staging && yarn deploy:staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: broadcast-service/example deployed
      - name: serverless deploy
        working-directory: ./packages/api
        run: yarn aws:profile:set --stage staging && yarn deploy:staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SENTRY_DNS: ${{ secrets.SENTRY_API_DNS }}
          SECRET: ${{ secrets.STAGING_CLUSTER_SECRET }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Create SSH Private Key
        run: echo "$SSH_KEY" > ~/.ssh/picnic && chmod 600 ~/.ssh/picnic
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/picnic
        name: register ssh agent
      - run: yarn build
        working-directory: ./packages/server
      - run: yarn deploy
        working-directory: ./packages/server
        env:
          CLUSTER_API: ${{ secrets.STAGING_CLUSTER_API }}
          CLUSTER_SECRET: ${{ secrets.STAGING_CLUSTER_SECRET }}
          PUBLIC_IP: ${{ env.SERVER_PUBLIC_IP }}
          SENTRY_ENVIRONMENT: ${{env.ENVIRONMENT_NAME}}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: Mediasoup Server deployed
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}
          SLACK_CHANNEL: deploys
          SLACK_TITLE: Mediasoup Server FAILED
          SLACK_COLOR: "#2eb886"
        if: failure()
