name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: serverless deploy
        working-directory: ./packages/api
        run: yarn deploy:staging
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Create SSH Private Key
        run: echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/picnic && chmod 600 ~/.ssh/picnic
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: pm2 deploy
        working-directory: ./packages/server
        run: yarn deploy:staging
