# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Lint & Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: actions/cache@v2
        with:
          path: "~/.yarn/berry/cache/"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: cp .yarnrc.yml.template .yarnrc.yml
      - run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: actions/cache@v2
        with:
          path: "~/.yarn/berry/cache/"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: cp .yarnrc.yml.template .yarnrc.yml
      - run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn lint
  typescript-api:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: actions/cache@v2
        with:
          path: "~/.yarn/berry/cache/"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: cp .yarnrc.yml.template .yarnrc.yml
      - run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: tsc --noEmit
        working-directory: ./packages/api
  typescript-client:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: actions/cache@v2
        with:
          path: "~/.yarn/berry/cache/"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: cp .yarnrc.yml.template .yarnrc.yml
      - run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: tsc --noEmit
        working-directory: ./packages/client
  typescript-server:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: actions/cache@v2
        with:
          path: "~/.yarn/berry/cache/"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: cp .yarnrc.yml.template .yarnrc.yml
      - run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: tsc --noEmit
        working-directory: ./packages/server
